app: lexet
ingredients:
  sources:
    - deb http://us.archive.ubuntu.com/ubuntu/ xenial xenial-updates xenial-security main universe
    - deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main universe
    - deb http://us.archive.ubuntu.com/ubuntu/ xenial-security main universe
  ppas:
    - ubuntu-elisp/ppa
  packages:
    # - python3
    # - php-cli
    - emacs-snapshot
    # - pylint3
    # - shellcheck
  script:
    - wget -c https://raw.githubusercontent.com/mu-editor/mu/master/conf/mu.codewith.editor.png
    - cp ./mu.codewith.editor.png ./lexet.png
script:
  - ln -s ./usr/bin/etags-snapshot ./usr/bin/emacs
  - cp ../lexet.png ./lexet.png
  - ln -s ./lexet.png ./usr/share/icons/hicolor/256x256/
  - cat > lexet.desktop <<EOF
  - [Desktop Entry]
  - Type=Application
  - Name=Lexet
  - Comment=IDE
  - Icon=lexet
  - Exec=emacs %F
  - Terminal=false
  - Categories=Application;Development;
  - Keywords=Editor;
  - EOF
  # - ln -s ./lexet.desktop ./usr/share/applications/lexet.desktop
