app: lexet
ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main universe
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
    - deb http://archive.ubuntu.com/ubuntu bionic main
    - deb http://archive.ubuntu.com/ubuntu bionic-updates main
    - deb http://archive.ubuntu.com/ubuntu bionic-security main
    - deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
    - deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
    - deb http://security.ubuntu.com/ubuntu bionic-security main
    - deb http://security.ubuntu.com/ubuntu bionic-security main restricted
    - deb http://security.ubuntu.com/ubuntu bionic-security universe
    - deb http://security.ubuntu.com/ubuntu bionic-security multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
  ppas:
    - ubuntu-elisp/ppa
  packages:
    # - python3-venv
    # - python3-pip
    # - python3
    # - php-cli
    - emacs-snapshot
    # - pylint3
    # - shellcheck
  script:
    - wget -c https://raw.githubusercontent.com/mu-editor/mu/master/conf/mu.codewith.editor.png
    - cp ./mu.codewith.editor.png ./lexet.png
script:
  - ln -s ./etags-snapshot ./usr/bin/emacs
  - cp ../lexet.png ./lexet.png
  - ln -s ./lexet.png ./usr/share/icons/hicolor/256x256/
  - cat > lexet.desktop <<EOF
  - [Desktop Entry]
  - Type=Application
  - Name=Lexet
  - Comment=IDE
  - Icon=lexet
  - Exec=emacs %F
  - Terminal=false
  - Categories=Application;Development;
  - Keywords=Editor;
  - MimeType=text/x-python3;
  - EOF
  # - ln -s ./lexet.desktop ./usr/share/applications/lexet.desktop
